-- Users table (handled by Supabase Auth)
-- Extend with profiles
create table profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  avatar_url text,
  user_type text check (user_type in ('farmer', 'buyer')),
  location text,
  phone_number text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Products table
create table products (
  id bigint generated by default as identity primary key,
  farmer_id uuid references profiles not null,
  name text not null,
  description text,
  price numeric not null,
  quantity numeric not null,
  unit text not null,
  category text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Market prices table
create table market_prices (
  id bigint generated by default as identity primary key,
  crop text not null,
  price numeric not null,
  location text not null,
  source text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Orders table
create table orders (
  id bigint generated by default as identity primary key,
  buyer_id uuid references profiles not null,
  farmer_id uuid references profiles not null,
  product_id bigint references products not null,
  quantity numeric not null,
  total_price numeric not null,
  status text not null default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table profiles enable row level security;
alter table products enable row level security;
alter table market_prices enable row level security;
alter table orders enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Similar policies for other tables...
